export const translations = {
    ru: {
        welcome: "Добро пожаловать в OTS",
        welcomeSub: "Создайте новый кошелек или импортируйте существующий для начала работы.",
        createWallet: "Создать новый кошелек",
        importWallet: "Импортировать Private Key",
        wallet: "Кошелек",
        balance: "Баланс OTS",
        stake: "Стейк: {0} OTS",
        receive: "Получить",
        send: "Отправить",
        staking: "Стейкинг",
        recentTx: "Последние транзакции",
        emptyHistory: "История пуста",
        depositTx: "Депозит стейка",
        inTx: "Входящий перевод",
        outTx: "Исходящий перевод",
        contracts: "Смарт-Контракты",
        deploy: "Деплой контракта",
        deploySub: "Опубликовать новый код в сеть",
        call: "Вызов контракта",
        callSub: "Взаимодействие с существующим",
        settings: "Настройки",
        language: "Язык",
        myWallets: "Мои Кошельки",
        copyAddr: "Скопировать адрес",
        copied: "Скопированно!",
        rename: "Переименовать",
        deleteKey: "Удалить ключ",
        newWalletParams: "Создать новый кошелек",
        importParams: "Импортировать Private Key",
        sendOts: "Отправить OTS",
        addrPlaceholder: "Адрес (public key)",
        sumPlaceholder: "Сумма OTS",
        commentPlaceholder: "Комментарий (необязательно)",
        sending: "Отправка...",
        sent: "Отправлено",
        yourAddr: "Ваш адрес",
        stakeMinInfo: "Заблокируйте минимум {0} OTS, чтобы стать валидатором",
        stakeSum: "Стейк (сумма)",
        doStake: "Внести стейк",
        doDeploy: "Задеплоить в сеть",
        txSent: "Транзакция отправлена!",
        contractAddr: "Адрес контракта:",
        close: "Закрыть",
        callAddr: "Адрес контракта",
        callSum: "Сумма (необязательно)",
        callGasLim: "Лимит газа",
        callArgs: 'Аргументы: {"method": "..."}',
        doCall: "Выполнить вызов",
        enterPriv: "Введите приватный ключ:",
        newName: "Новое имя:",
        netError: "Сеть не подключена",
        sendError: "Ошибка отправки: ",
        stakeSuccess: "Запрос на стейкинг отправлен!",
        callSuccess: "Вызов контракта отправлен!",
        estimatedCost: "Рассчитанная стоимость",
        txError: "Ошибка транзакции{0}",
        noFunds: "Недостаточно средств ({0} > {1})"
    },
    en: {
        welcome: "Welcome to OTS",
        welcomeSub: "Create a new wallet or import an existing one to get started.",
        createWallet: "Create new wallet",
        importWallet: "Import Private Key",
        wallet: "Wallet",
        balance: "OTS Balance",
        stake: "Stake: {0} OTS",
        receive: "Receive",
        send: "Send",
        staking: "Staking",
        recentTx: "Recent transactions",
        emptyHistory: "History is empty",
        depositTx: "Stake deposit",
        inTx: "Incoming transfer",
        outTx: "Outgoing transfer",
        contracts: "Smart Contracts",
        deploy: "Deploy contract",
        deploySub: "Publish new code to the network",
        call: "Call contract",
        callSub: "Interact with an existing one",
        settings: "Settings",
        language: "Language",
        myWallets: "My Wallets",
        copyAddr: "Copy address",
        copied: "Copied!",
        rename: "Rename",
        deleteKey: "Delete key",
        newWalletParams: "Create new wallet",
        importParams: "Import Private Key",
        sendOts: "Send OTS",
        addrPlaceholder: "Address (public key)",
        sumPlaceholder: "Amount OTS",
        commentPlaceholder: "Comment (optional)",
        sending: "Sending...",
        sent: "Sent",
        yourAddr: "Your address",
        stakeMinInfo: "Lock at least {0} OTS to become a validator",
        stakeSum: "Stake amount",
        doStake: "Stake",
        doDeploy: "Deploy to network",
        txSent: "Transaction sent!",
        contractAddr: "Contract address:",
        close: "Close",
        callAddr: "Contract address",
        callSum: "Amount (optional)",
        callGasLim: "Gas limit",
        callArgs: 'Arguments: {"method": "..."}',
        doCall: "Execute call",
        enterPriv: "Enter private key:",
        newName: "New name:",
        netError: "Network is not connected",
        sendError: "Send error: ",
        stakeSuccess: "Staking request sent!",
        callSuccess: "Contract call sent!",
        estimatedCost: "Estimated cost",
        txError: "Transaction error{0}",
        noFunds: "No funds ({0} > {1})"
    }
};